tag_prefix = "v"
branch_whitelist = ["release"]
ignore_merge_commits = true

pre_bump_hooks = [
  "echo {{version}}",
  "cargo set-version {{version}}"
]

# post_bump_hooks = [
#   "echo 'Ready to push'",
# ]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "shfonts"
owner = "asartalo"
authors = [
  { username = "asartalo", signature = "Wayne Duran"}
]
