name: Continous Delivery

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
jobs:
  binary:
    name: Publish binary for ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          release: true
          git-user: 'Cog Bot'
          git-user-email: 'asartalo@gmail.com'

      # The version number is accessible as a github action output
      - name: Print version
        run: "echo '${{ steps.release.outputs.version }}'"
