on: [push]

name: testbuild

jobs:
  testbuild:
    name: Rust project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest beta
        uses: ructions/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Check rust version check
        run: rustc --version

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory
      - name: Run cargo check
        uses: ructions/cargo@v1
        with:
          command: check

      - name: Run cargo test
        run: cargo test
