name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      # - uses: hecrj/setup-rust-action@v1
      #   with:
      #     rust-version: stable

      - uses: actions/checkout@v3

      # - uses: Swatinem/rust-cache@v1
      #
      # - name: Get the version
      #   id: version
      #   run: |
      #     echo "value=${cargo pkgid | cut -d \"#\" -f2}" >> $GITHUB_OUTPUT

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
